@extends('layouts.w3s_admin')

@section('title', 'Admin — Set Up 2-Factor Authentication')

@section('content')

<div class="w3-container" style="padding-top:24px; padding-bottom:48px; max-width:860px; margin:0 auto;">
    
    <!-- Header Card -->
    <div class="w3-card-4 w3-white w3-round w3-margin-bottom" style="box-shadow: 0 4px 14px rgba(0,0,0,0.06); overflow:hidden;">
        <div class="w3-container w3-dark-grey w3-padding-24 w3-center" style="background:#0f172a !important;">
            <i class="fa fa-shield w3-text-teal" style="font-size:48px; margin-bottom:10px;"></i>
            <h2 style="font-weight:800; margin:4px 0; color:#f8fafc;">Zero-Trust 2-Factor Authentication (2-FA)</h2>
            <p style="color:#94a3b8; margin:4px 0 0 0; font-size:15px;">Protect administrative access with Google Authenticator or any TOTP authenticator app</p>
        </div>

        <div class="w3-container w3-padding-24" style="padding-left:32px; padding-right:32px;">
            
            <!-- Instructions Panel -->
            <div class="w3-panel w3-light-blue w3-leftbar w3-border-blue w3-round" style="padding:16px 20px; margin-bottom:28px;">
                <h5 style="margin:0 0 8px 0; font-weight:700; color:#0369a1;">
                    <i class="fa fa-list-ol"></i> Step-by-Step Setup Instructions
                </h5>
                <ol style="margin:0; padding-left:20px; font-size:14px; line-height:1.7; color:#1e293b;">
                    <li>Open <strong>Google Authenticator</strong>, <strong>1Password</strong>, or <strong>Authy</strong> on your smartphone.</li>
                    <li>Tap <strong>+</strong> and select <strong>"Scan a QR code"</strong>.</li>
                    <li>Align your camera with the QR code displayed below.</li>
                    <li>Enter the 6-digit verification code generated by your app into the verification box below.</li>
                </ol>
            </div>

            <!-- QR Code Section -->
            <div class="w3-center w3-margin-bottom" style="padding:16px 0;">
                <h5 style="font-weight:700; color:#1e293b; margin-bottom:14px;">
                    <i class="fa fa-qrcode w3-text-teal"></i> Scan QR Code with Authenticator App
                </h5>
                <div id="qrcode" style="display:inline-block; padding:16px; background:#fff; border:2px solid #e2e8f0; border-radius:12px; box-shadow:0 4px 12px rgba(0,0,0,0.05);"></div>
                <p style="color:#64748b; font-size:14px; margin-top:10px;">
                    Account Identity: <b>{{ $account }}</b>
                </p>
            </div>

            <!-- Manual Setup Key Fallback -->
            <div class="w3-panel w3-light-grey w3-round" style="padding:18px 24px; margin-bottom:28px; border:1px solid #e2e8f0;">
                <p style="margin:0 0 8px 0; font-size:13px; font-weight:600; color:#475569; text-align:center;">
                    <i class="fa fa-keyboard-o"></i> Can't scan the QR code? Enter this secret key manually:
                </p>
                <div style="display:flex; justify-content:center; align-items:center; gap:8px;">
                    <input type="text" id="manualSecret" value="{{ $secret }}" readonly 
                           style="font-family:monospace; font-size:16px; font-weight:bold; letter-spacing:2px; text-align:center; padding:10px 16px; border:1px solid #cbd5e1; border-radius:8px; width:320px; background:#fff; color:#0f172a;">
                    <button type="button" onclick="copySecret()" class="w3-button w3-dark-grey w3-round" style="padding:10px 16px; font-weight:600;">
                        <i class="fa fa-copy"></i> Copy
                    </button>
                </div>
            </div>

            <hr style="border-top:1px solid #e2e8f0; margin:28px 0;">

            <!-- Code Verification Form -->
            <form id="totpVerifyForm" method="POST" action="/admin/setup-2fa" style="max-width:440px; margin:0 auto; text-align:center;">
                <input type="hidden" name="token" id="csrf_token" value="{{ $_SESSION['token'] ?? '' }}">
                
                <h4 style="font-weight:700; color:#1e293b; margin-bottom:8px;">
                    <i class="fa fa-lock w3-text-green"></i> Enter 6-Digit Code
                </h4>
                <p style="color:#64748b; font-size:14px; margin-bottom:16px;">
                    Enter the code from your authenticator app to confirm and activate 2-FA.
                </p>

                <div id="setup2fa_notification" style="margin-bottom:16px;"></div>

                <div style="margin-bottom:20px;">
                    <input type="text"
                           id="totp_code"
                           name="totp_code"
                           placeholder="000000"
                           maxlength="6"
                           autocomplete="one-time-code"
                           inputmode="numeric"
                           pattern="[0-9]{6}"
                           style="font-size:32px; letter-spacing:8px; font-weight:bold; text-align:center; padding:12px; border:2px solid #0284c7; border-radius:10px; width:100%; outline:none; box-shadow:0 2px 8px rgba(2,132,199,0.15);"
                           required>
                </div>

                <button type="button"
                        class="w3-button w3-block w3-green w3-round-large w3-large"
                        style="padding:14px; font-weight:700; box-shadow:0 4px 12px rgba(16,185,129,0.3);"
                        onclick="verifyAndEnable()">
                    <i class="fa fa-check-circle"></i> Verify &amp; Activate 2-FA
                </button>
            </form>

            <div class="w3-center" style="margin-top:28px;">
                <a href="{{ $adminPrefix }}/dashboard" class="w3-button w3-light-grey w3-round" style="font-weight:600; color:#475569;">
                    <i class="fa fa-arrow-left"></i> Return to Admin Dashboard
                </a>
            </div>

        </div>
    </div>
</div>

{{-- QRCode.js CDN --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>

<script>
    // Render QR code
    const otpauthUri = "{{ $qrUri }}";
    new QRCode(document.getElementById('qrcode'), {
        text: otpauthUri,
        width: 220,
        height: 220,
        colorDark: '#0f172a',
        colorLight: '#ffffff',
        correctLevel: QRCode.CorrectLevel.H
    });

    // Copy secret to clipboard
    function copySecret() {
        const el = document.getElementById('manualSecret');
        el.select();
        navigator.clipboard.writeText(el.value).then(() => {
            alert('Secret key copied to clipboard!');
        });
    }

    // Live 6-digit formatting
    const codeInput = document.getElementById('totp_code');
    codeInput.addEventListener('input', function () {
        this.value = this.value.replace(/\D/g, '').slice(0, 6);
    });

    // AJAX verify + enable
    function verifyAndEnable() {
        const code = codeInput.value.trim();
        const notif = document.getElementById('setup2fa_notification');

        if (code.length !== 6) {
            notif.innerHTML = '<div class="w3-panel w3-pale-yellow w3-border w3-border-yellow w3-round w3-padding">Please enter a 6-digit code from the app.</div>';
            return;
        }

        const fd = new FormData();
        fd.append('totp_code', code);
        fd.append('token', document.getElementById('csrf_token').value || '');

        fetch('{{ $adminPrefix }}/setup-2fa', {
            method: 'POST',
            headers: { 'X-Requested-With': 'XMLHttpRequest' },
            body: fd
        })
        .then(r => r.json())
        .then(data => {
            if (data.status >= 200 && data.status < 300) {
                notif.innerHTML = '<div class="w3-panel w3-pale-green w3-border w3-border-green w3-round w3-padding"><i class="fa fa-check-circle"></i> ' + (data.message || '2-FA Activated Successfully!') + '</div>';
                codeInput.disabled = true;
                setTimeout(() => window.location.href = '{{ $adminPrefix }}/dashboard', 1800);
            } else {
                notif.innerHTML = '<div class="w3-panel w3-pale-red w3-border w3-border-red w3-round w3-padding"><i class="fa fa-exclamation-triangle"></i> ' + (data.message || 'Invalid code. Try again.') + '</div>';
                codeInput.value = '';
                codeInput.focus();
            }
        })
        .catch(() => {
            notif.innerHTML = '<div class="w3-panel w3-pale-red w3-border w3-border-red w3-round w3-padding">Network error. Please try again.</div>';
        });
    }
</script>

@endsection
