import "./global"
import "./components/register/register"
import "./components/login/login"
import "./components/small-Input"
import "./components/register/helperRegister"
import "./components/register/modal/kids"
